import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { UserProvider } from "@/contexts/UserContext";
import { ErrorProvider } from "@/contexts/ErrorContext";
import { LoaderProvider } from "@/contexts/LoaderContext";
import { GlobalLoader } from "@/components/common/GlobalLoader";
import AlertProvider from "@/components/alerts/AlertProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <LoaderProvider>
          <UserProvider>
            <AlertProvider>
              <GlobalLoader />
              <ErrorProvider>
                {children}
              </ErrorProvider>
            </AlertProvider>
          </UserProvider>
        </LoaderProvider>
      </body>
    </html>
  );
}

