import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { UserProvider } from "@/context/UserContext";
import { ThemeProvider } from '../context/ThemeContext';
import { ErrorProvider } from "@/context/ErrorContext";
import { LoaderProvider } from "@/context/LoaderContext";
import { GlobalLoader } from "@/components/common/GlobalLoader";
import AlertProvider from "@/components/alerts/AlertProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <ThemeProvider>
            <AlertProvider>
            <LoaderProvider>
              <GlobalLoader />
            <ErrorProvider>
              {children}
            </ErrorProvider>
          </LoaderProvider>
                      </AlertProvider>

          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
