version: "3.9"

services:
  backend:
    image: m3ntha_backend:latest
    container_name: m3ntha_backend
    build: ../backend
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/app
    networks:
      - shared_network

  frontend:
    image: m3ntha_frontend:latest
    container_name: m3ntha_frontend
    build: ../frontend
    env_file:
      - ../frontend/.env
    volumes:
      - ../frontend:/app
    networks:
      - shared_network
    depends_on:
      - backend

networks:
  shared_network:
    external: true
