version: "3.9"

services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    env_file:
      - ../backend/.env
    volumes:
      - ../backend:/app
    networks:
      - shared_network

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/mentha-auth
      - BETTER_AUTH_SECRET=GMy91JaVDufDw9A5zGlQ1IihHEXXHDHQ
      - BETTER_AUTH_URL=http://localhost:3000
    networks:
      - shared_network
    depends_on:
      - backend

networks:
  shared_network:
    external: true
